name: Auto PR (DVWA security fixes)

on:
  workflow_dispatch:
  schedule:
    - cron: "14 5 * * 1"   # every Monday 05:14 UTC

# allow GITHUB_TOKEN to push and open PRs
permissions:
  contents: write
  pull-requests: write

concurrency:
  group: autopatch-${{ github.ref }}
  cancel-in-progress: false

jobs:
  autopatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history, keep credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Semgrep (user install; add to PATH)
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1
        run: |
          python -m pip install --upgrade pip
          pip install --user "semgrep>=1.76.0"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Semgrep scan (report only)
        run: |
          semgrep --metrics=off \
                  --config=p/php \
                  --config=p/owasp-top-ten \
                  --json --output semgrep.json || true

      - name: Semgrep autofix (if rules file exists)
        if: ${{ hashFiles('.semgrep-fixes.yml') != '' }}
        run: semgrep --metrics=off --config .semgrep-fixes.yml --fix || true

      # simple hardening so we always have a demonstrable change
      - name: Fallback patch (ensure at least one change)
        run: |
          shopt -s globstar || true
          changed=0
          for f in **/*.php; do
            [ -f "$f" ] || continue
            # escape echoed GET params (very conservative)
            sed -E -i "s/echo[[:space:]]+\$_GET\[(.+)\];/echo htmlspecialchars(\$_GET[\1], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');/g" "$f" && changed=1 || true
          done
          # create a tiny marker if nothing changed so PR action always has something to commit
          if [ "$changed" -eq 0 ]; then
            echo "autopatch run $(date -u +%FT%TZ)" >> .autopatch.log
          fi

      - name: Upload semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.json
          if-no-files-found: ignore

      - name: Create security PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: security/auto-fix
          base: master                # change to 'main' if your default branch is main
          commit-message: "chore(security): automated fixes"
          title: "chore(security): automated fixes (DVWA)"
          body: |
            Automated PR created by GitHub Actions.

            - Semgrep scan (artifact attached)
            - Auto-hardening for echoed request params (XSS)
            - Any additional fixes from `.semgrep-fixes.yml` if present

            Please review and merge.
          labels: |
            security
            automated
